# Copyright 2023 SECO Mind Srl
# SPDX-License-Identifier: Apache-2.0

name: nix-check

permissions:
  contents: read

on:
  workflow_call:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          # Don't send the diagnostics automatically
          diagnostic-endpoint: ""
      - run: nix flake check
